---

- name: ensure apt official nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  tags: [packages,nginx]

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} nginx"
  tags: [packages,nginx]

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} nginx"
  tags: [packages,nginx]

- name: NGINX | Updating apt cache
  apt:
    update_cache: yes
  tags: [packages,nginx]

- name: install the nginx packages
  apt: name=nginx state=present
  with_items:
    - python-selinux
    - nginx
  environment: { RUNLEVEL: 1}
  tags: [packages,nginx]

- name: config nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: flush handlers to apply config changes
  meta: flush_handlers

- name: ensure nginx is running
  service: name=nginx state=started

